version: 2.1

jobs:
  lint:
    docker:
      - image: alpine:3.14.2
    steps:
      - checkout
      - run: 
          name: Install dependencies and Lint app files 
          command: make all
  build:
    docker:
      - image: alpine:3.14.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and deploy to DockerHub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker build . -t $DOCKER_USERNAME/capstone-devops:$TAG
            docker push $DOCKER_USERNAME/capstone-devops:$TAG
  deploy:
    docker:
      - image: alpine:3.14.2
    steps:
      - checkout
      - run: echo "this is the build job"

workflows:
  rolling_deployment:
    jobs:
      - lint
      - build:
          requires: 
            - lint
      - deploy:
          requires:
            - build
