version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: sudo make install
      - run: 
          name: Lint app files 
          command: make lint
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and deploy to DockerHub
          command: |
            TAG=$VERSION_TAG-$CIRCLE_BUILD_NUM
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker build . -t $DOCKER_USERNAME/capstone-devops:$TAG
            docker push $DOCKER_USERNAME/capstone-devops:$TAG
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
          curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          sudo chmod +x kubectl && sudo mv kubectl /usr/local/bin
          mkdir ~/.kube
          echo $KUBECTL_CONFIG | base64 -di; echo
          kubectl get nodes

workflows:
  rolling_deployment:
    jobs:
      - lint
      - build:
          requires: 
            - lint
      - deploy:
          requires:
            - build
