version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
          make all
  
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          DATE=$(date +%Y%d%m)
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker build . -t $DOCKER_USERNAME/capstone-devops:$DATE-$CIRCLE_BUILD_NUM
          docker push $DOCKER_USERNAME/capstone-devops:$DATE-$CIRCLE_BUILD_NUM
  
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "this is the build job"

workflows:
  build_and_test:
    jobs:
      - lint
      - build:
          requires: 
            - lint
      - deploy:
          requires:
            - build
